### PR TITLE
added timeouts and continue

### PR DESCRIPTION
**Pull request by dmitrinove**
added timeouts to avoid download hang for minutes or more
added continue getting partially downloaded files
added user agent header to all connection
added environment variable to specify user agent string added download info

removed tmp-dir directory

I eliminated the use of uuids for temporary files because it becomes difficult to manage temporary downloads.
I also eliminated creating the tmp-dir directory, I hope I didn't eliminate something useful

### CODE REVIEW

**Comment by ltsdw** [comment]
@dmitrinove Hey, really great additions I didn't have time to test it thoroughly, but it seems fine to me from the little I tested 😃 

But I would like to ask, if it isn't much of a trouble, to you create a separate commit to each additional/removal please. Thank you.

**Comment by ltsdw** [comment]
@dmitrinove Also, it looks like you removing tmp-dir/uuids parts broke the download of nested files inside sub directories.
You can have a look at #10 and #11 . If you can fix those I can merge it.

**Comment by dmitrinove** [comment]
As I wrote, I deleted it because the use of random uuids makes it impossible to recover an interrupted download.
I could try to restore the use of tmp-dir but I need a sample gofile link for testing, the links in thread [#10](https://github.com/ltsdw/gofile-downloader/issues/10) are expired.

please create me a link with small files that recreates the recursion problem, if I find a permanent solution I will create a new commit.

then we can try to create incremental commits for each new feature

**Comment by ltsdw** [comment]
you can create this environment as a guest, it isn't necessary having an account.

Just go to gofile -> My Files, and there you can create some directories, sub directories and inside these you can put empty text file with different filenames, this way you can see if while downloading stuff were put on its correct directory.

**Comment by dmitrinove** [comment]
with the latest changes it is possible to download directories and sub directories.

**Comment by ltsdw** [comment]
Seems all right now, it would have been better to have split the first commit into small one, this way is easier to track regressions. But we'll work with that if any were introduced and not catch in my tests.

Again, thank you so much, really great additions :)

**Pull request merged**
